### PR TITLE
Remove allen part of atlalign

### PR DESCRIPTION
**Pull request by EmilieDel**

### CODE REVIEW

**Review by Stannislav — APPROVED** [review]
Cool, thanks!

Did `atlalign` not use its module `atlalign.allen` internally at all? 🤔 Then it doesn't even need to depend on `atldld`? Because if it does we would need to add it to the dependencies...

**Comment by EmilieDel** [comment]
Thanks for your feedback!

I will maybe wait to double check with @jankrepl but I did a grep on the package and did not find any reference to the `allen` part in the code!

**Comment by Stannislav** [comment]
> Thanks for your feedback!
> 
> I will maybe wait to double check with @jankrepl but I did a grep on the package and did not find any reference to the `allen` part in the code!

Yes, same, let's maybe wait for @jankrepl to clarify.

**Comment by jankrepl** [comment]
AFAIK the `allen` subpackage was not used elsewhere in the code:) Therefore I would say that this PR is ready to be merged. Maybe we could mention somewhere (e.g. `README.md`) that there is a new repo that replaces it?

**Comment by EmilieDel** [comment]
Hello @jankrepl! Thanks for the feedback! Great idea for the `README.md`, I just added one line in 37639f7!

**Pull request merged**
